version: '3.8'

services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-m_db}
      - POSTGRES_USER=${DB_USER:-m_admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-m_12345678}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - DB_NAME=${DB_NAME:-m_db}
      - DB_USER=${DB_USER:-m_admin}
      - DB_PASSWORD=${DB_PASSWORD:-m_12345678}
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx nodemon --inspect=0.0.0.0:9229 src/app.js

volumes:
  postgres_data: